name:                hammy
version:             0.1.0.0
github:              "EddieTheEd/hammy"
license:             BSD-3-Clause
author:              "EddieTheEd"
maintainer:          "ed@toomwn.xyz"
copyright:           "2024 EddieTheEd"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EddieTheEd/hammy#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk
- gi-gtk-hs
- haskell-gi-base
- text >= 1.2.4.1
- gi-gdk
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hammy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hammy

tests:
  hammy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hammy
